// Frontend/src/app/login/login.component.ts
import {Component} from '@angular/core';
import {sha256} from "js-sha256";
import {ApiService} from "../api.service";

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent {
  constructor(private apiService: ApiService) {
  }

  setBearerToken(token: string) {
    const fullToken = `Bearer ${token}`;
    localStorage.setItem("Authorization", token);
  }

  private _username: string = "";
  private _password: string = "";

  keyUpUsername(event: KeyboardEvent) {
    this._username = (event.target as HTMLInputElement).value;
  }

  keyUpPassword(event: KeyboardEvent) {
    this._password = (event.target as HTMLInputElement).value;
  }

  handleLogin(event: Event) {
    event.preventDefault();
    if (this._username.trim() && this._password) {
      const e_username: string = this._username.trim().toLowerCase();
      const e_password: string = sha256(this._password);
      // Remove log later
      console.log(`Username: ${e_username} | Password: ${e_password}`);

      this.apiService.loginPost(e_username, e_password).subscribe({
        next: (response: any) => {
          console.log("Login successful", response);
          this.setBearerToken(response.token);
        },
        error: (error) => {
          console.log("Login failed", error);
        }
      });
    }
  }
}

<div class="container">
  <h1>Le Chat</h1>
  <article>
    <form *ngIf="isLogin">
      <input id="username" type="text" placeholder="Username" required (keyup)="keyUpUsername($event)"/>
      <input id="password" type="password" placeholder="Password" required (keyup)="keyUpPassword($event)"/>
      <small>Your data is stored safely and we do not have access to it.</small>

      <input type="submit" role="button" value="Login" (click)="handleLogin($event)"/>
      <input type="button" role="button" value="Register" (click)="isLogin = false"/>
    </form>

    <form *ngIf="!isLogin">
      <input id="registerUsername" type="text" placeholder="Username" required (keyup)="keyUpUsername($event)"/>
      <input id="registerPassword" type="password" placeholder="Password" required (keyup)="keyUpPassword($event)"/>
      <input id="registerPasswordRepeat" type="password" placeholder="Repeat password" required
             (keyup)="keyUpPasswordRepeat($event)" [attr.aria-invalid]="!passwordRepeatValid"/>
      <small>Your data is stored safely and we do not have access to it.</small>

      <input type="submit" role="button" value="Register" (click)="handleRegister($event)"/>
      <button type="button" class="outline" (click)="isLogin = true">Back to login</button>
    </form>

<!--    <button [ngClass]="loginSuccessful ? 'outline' : 'outline secondary'" (click)="handleCheckLogin($event)">Test login-->
<!--      status-->
<!--    </button>-->
  </article>
</div>

// frontend/src/sites/Login.tsx
import {useState} from 'react';
import '../css/login.css';
import {sha256} from 'js-sha256';

export default function Login() {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');

  const handleLogin = async (e_username: string, e_password: string) => {
    try {
      const requestBody = {
        username: e_username,
        password: e_password,
      };

      const response = await fetch('http://localhost:5147/api/login', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(requestBody),
      });
      if (response.ok) {
        return await response.json();
      } else {
        return false;
      }
    } catch (error) {
      console.error('An error occurred:', error);
    }
  };

  return (
    <div className="Login container">
      <h1 className='main-title'>Le Chat</h1>
      <article>
        <form>
          <input id="username" type="text" name="username" placeholder="Username" required value={username}
                 onChange={(e) => setUsername(e.target.value)} aria-invalid={!username.trim()}/>
          <input id="password" type="password" name="password" placeholder="Password" required value={password}
                 onChange={(e) => setPassword(e.target.value)} aria-invalid={!password}/>
          <small>Your data is stored safely and we do not have access to it.</small>
          <button type='submit' onClick={(e) => {
            e.preventDefault();
            if (username.trim() && password) {
              const e_username: string = username.trim().toLowerCase() //sha256(username.trim());
              const e_password: string = sha256(password);

              handleLogin(e_username, e_password).then(r => {
                if (!r) {
                  console.error("Login fail.");
                  return;
                }
                localStorage.setItem("Authorization", "Bearer " + r.token);
              });
              
              // Cookie acquired -> redirect to overview site
            }
          }}>Login
          </button>
        </form>
      </article>
    </div>
  );
}
